package com.example.czechfoolapp.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFFA70FA4)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFD7F5)
val md_theme_light_onPrimaryContainer = Color(0xFF380037)
val md_theme_light_secondary = Color(0xFF4E6700)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFC5F350)
val md_theme_light_onSecondaryContainer = Color(0xFF151F00)
val md_theme_light_tertiary = Color(0xFF006874)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFF98F0FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001F24)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1F1A1D)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1F1A1D)
val md_theme_light_surfaceVariant = Color(0xFFEEDEE7)
val md_theme_light_onSurfaceVariant = Color(0xFF4E444B)
val md_theme_light_outline = Color(0xFF80747B)
val md_theme_light_inverseOnSurface = Color(0xFFF8EEF2)
val md_theme_light_inverseSurface = Color(0xFF342F32)
val md_theme_light_inversePrimary = Color(0xFFFFABF2)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFFA70FA4)
val md_theme_light_outlineVariant = Color(0xFFD1C2CB)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFFABF2)
val md_theme_dark_onPrimary = Color(0xFF5B005A)
val md_theme_dark_primaryContainer = Color(0xFF810080)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFD7F5)
val md_theme_dark_secondary = Color(0xFFAAD635)
val md_theme_dark_onSecondary = Color(0xFF273500)
val md_theme_dark_secondaryContainer = Color(0xFF3A4D00)
val md_theme_dark_onSecondaryContainer = Color(0xFFC5F350)
val md_theme_dark_tertiary = Color(0xFF4FD8EC)
val md_theme_dark_onTertiary = Color(0xFF00363D)
val md_theme_dark_tertiaryContainer = Color(0xFF004F58)
val md_theme_dark_onTertiaryContainer = Color(0xFF98F0FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1F1A1D)
val md_theme_dark_onBackground = Color(0xFFE9E0E4)
val md_theme_dark_surface = Color(0xFF1F1A1D)
val md_theme_dark_onSurface = Color(0xFFE9E0E4)
val md_theme_dark_surfaceVariant = Color(0xFF4E444B)
val md_theme_dark_onSurfaceVariant = Color(0xFFD1C2CB)
val md_theme_dark_outline = Color(0xFF9A8D95)
val md_theme_dark_inverseOnSurface = Color(0xFF1F1A1D)
val md_theme_dark_inverseSurface = Color(0xFFE9E0E4)
val md_theme_dark_inversePrimary = Color(0xFFA70FA4)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFABF2)
val md_theme_dark_outlineVariant = Color(0xFF4E444B)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFA1009F)